stages:
    - test
    - staging

before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - apt-get update -qy
    - apt-get install -y python-dev python-pip python3-dev python3-pip python-numpy python3-numpy g++ make

test:
    stage: test
    script:
        - bash lifelib/tests/test_all.sh

staging:
    stage: staging
    script:
        - bash recompile.sh
        - getconf _NPROCESSORS_ONLN
        - ./apgluxe -v 0 -k '#gitlab' -i 1 -n 5000000
